version: "3.8"

services:
  backend:
    restart: always
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile.backend
    env_file: devops.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  redis:
    image: "redis:6.2-alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_db:/data

  postgres_db:
    image: "postgres:13.4-alpine"
    ports:
      - "5432:5432"
    env_file: devops.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile.celery
    env_file: devops.env
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
  redis_db: